# Generated by Django 4.0.2 on 2022-02-27 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tokens.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Plastic', 'Plastic'), ('Bio-degradable', 'Bio-degradable'), ('Medical or Clinical Wastes', 'Medical or Clinical Wastes'), ('Industrial Sources of Wastes', 'Industrial Sources of Wastes'), ('Electronic sources of waste', 'Electronic sources of waste')], default='Plastic', max_length=150)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('images', models.ImageField(upload_to=tokens.utils.upload_image)),
                ('message', models.TextField(max_length=200)),
                ('number', models.TextField(max_length=14)),
                ('is_done', models.BooleanField(default=False)),
                ('raised_date', models.DateField(auto_now_add=True)),
                ('done_date', models.DateField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catched_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
    ]
