# Generated by Django 4.0.2 on 2022-02-26 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tokens.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('geo_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True)),
                ('images', models.ImageField(upload_to=tokens.utils.upload_image)),
                ('message', models.TextField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('raised_date', models.DateField()),
                ('assigned_date', models.DateField()),
                ('done_date', models.DateField()),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
