# Generated by Django 4.0.2 on 2022-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='done_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='raised_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
