# Generated by Django 4.0.2 on 2022-02-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='category',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Bio-degradable', 'Bio-degradable'), ('Medical or Clinical Wastes', 'Medical or Clinical Wastes'), ('Industrial Sources of Wastes', 'Industrial Sources of Wastes'), ('Electronic sources of waste', 'Electronic sources of waste')], max_length=150),
        ),
    ]
