# Generated by Django 4.0.2 on 2022-02-26 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokens', '0004_remove_token_assigned_date_token_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catched_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tokens.token')),
            ],
        ),
    ]
