name: Main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      -*
env:
  IMAGE_NAME: greenify
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Which Runner
        run : |
               hostnamectl
               ifconfig
      - name: Build image
        run: sudo /usr/bin/docker build . --file Dockerfile --tag $IMAGE_NAME
      
